### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by purkhusid** [fsharp-editing/forge-templates#5]
Hey, just got a new Mac and I decided to go through creating a new class library with Ionide/Forge and noticed a few things that could be refined at some point. 

1. When creating a new class library the target framework is .Net 4.6.1 and therefore the build script don't work out of the box on Mac/Linux.
   - Possible solution 1: Target netstandard by default so that the template works out of the box on all operating systems. I can create a pull request if this is an acceptable solution.
   - Possible solution 2: Detect OS and only target full framework on Windows. If this solution is preferred then I could take a look at it if it does not require extensive knowledge of how the templateing engine works or if I could get some directions on how to add this functionality.
2. The `.paket/paket.exe` is ignored in the `.gitignore` file. This makes it so that if I create a  project using the template and then check it into source control, then the build scripts will not work if I do a clean checkout of my project.
   - Possible solution: Remove the `.paket/paket.exe` from the `.gitignore` file. I can create a pull request if this is an acceptable solution.

**Comment by Krzysztof-Cieslak** [comment]
1. The workaround for problems on Mac/Linux is described here - https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1#using-net-framework-as-targets-framework-the-osxunix-build-fails
2. Is fixed in e1095166b47e582968cfe84db0781d2c72f38a99
